### ISSUE TITLE
Improve style of text in `backticks`

### ISSUE THREAD

**Issue by chtaube** [dossist/moinmoin-memodump#35]
I added this definition to my `memodump.css` to improve the presentation of text in backticks (used in MoinMoin for small code snippets, filenames, …)

``` css
.backtick {
    background-color: #f9f2f4;
    border-radius: 4px 4px 4px 4px;
    color: #c7254e;
    font-size: 90%;
    padding: 2px 4px;
    white-space: nowrap;
}
```

The result looks like this:

![memodump_backtick](https://cloud.githubusercontent.com/assets/929763/4294013/6f7f71e6-3ddb-11e4-927e-1f9add2ddc20.png)

The definition is actually taken from a bootstrap theme for dokuwiki, but it looks great in MoinMoin/memodump, too!
