### ISSUE TITLE
Headings hidden behind fixed navbar on top

### ISSUE THREAD

**Issue by chtaube** [dossist/moinmoin-memodump#37]
When using anchors to jump to a heading within the page (just as `<<TableOfContents()>>` does), the heading is hidden behind the top navigation bar.

A fix for this is to set `padding-top` to an overly large value to push the content down and set `margin-top` negative to prevent large blank space above the headings.

Example for h2 and h3 headings (tested in Firebug only):

``` css
#content h2 {
    margin-bottom: 30px;
    margin-top: -35px;
    padding-top: 70px;
}
#content h3 {
    margin-bottom: 25px;
    margin-top: -25px;
    padding-top: 70px;
}
```

There may be better solutions, though.
